<div class="amis">
<div class="error"><?= $error ?></div>
<p><a href="index.php?page=profil&pseudo=<?= htmlentities($result->getPseudoExp()) ?>"><?= htmlentities($result->getPseudoExp()) ?></a></p>
<img style="width:100px;height:100px;display:inline-block"src="public/images/<?= htmlentities($expediteur->getPeudo()) ?>/<?= htmlentities($expediteur->getAvatar())?>" />
<div style="display:inline-block;text-align:center;vertical-align:top;margin-left:10%;width:40%;word-wrap: break-word">
<p>infos :</p><p><?= substr(htmlentities($expediteur->getApropos()), 0, 25) ?></p><p>...</p></div>


</div>

