<div class="pseudo_membre">
    <p>Bonjour <?= htmlentities($info->getPseudo()) ?></p>
    <a href="index.php?page=logout">logout</a>
</div>
<div class="menu">
    <ul>
        <li><a href="index.php?page=membre">Acceuil</a></li>
        <li><a href="index.php?page=update">Changer vos infos</a></li>
        <li><a href="index.php?page=liste_membres">Les membres</a></li>
        <li><a href="index.php?page=amisUser">Vos amis</a></li>
        <li><a href="index.php?page=invitation">Invitations</a></li>
        <li><a href="index.php?page=messages">Messages</a></li>
        <li class="nbr"><?= $countAll ?> membres</li>
    </ul>
</div>
