<div class="login">
    <h1>Connection</h1>
    <div class="error"><?php echo $error ; ?></div>
<form action="" method="POST">
    <div><label>pseudo<input type="text" name="pseudo" /></div>
    <div><label>password<input type="password" name="password" /></div>
    <div><input type="submit" value="connection" name="submit" /></div>
</form>
</div>
<a href="index.php?page=register">creer un compte</a>
<div style="overflow:hidden"></div>
<a style="float:right" href='index.php?page=reset_password'>Mot de pass oublié ?</a>
