<!DOCTYPE html>
<html>
    <head>
        <title>titre</title>
        <!--<link type="text/css" rel="stylesheet" href="public/style/reset.css"/>-->
        <link type="text/css" rel="stylesheet" href="public/style/site.css"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"    
              integrity="sha384-  BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script type="text/jascript" src="public/js/main.js"></script>
    <head>
        <body>
            <div class="body">
                <div class="container">

    <?php 

if(isset($_SESSION['pseudo']))
{
    require('apps/header_membre.php');
}
else
{
    require('apps/header.php');
}
    
    require('apps/content.php');
    require('apps/footer.php');


    ?>


    

                </div>
            </div>
        <script type="text/javascript" src="public/js/main.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>

</html>
