
    <div class="update">
        <h3>changez vos infos </h3>
        <div class="error"><?= $error ?></div>
            <form action="" method="POST">
                <label for="situation">Votre situation</label>
                <select name="situation">
                    <option value="Celibataire">Celibataire</option>
                    <option value="En couple">En couple</option>
                </select></br>
                <label for="email">Votre email : </label>
                <input type="text" value="<?= htmlentities($info->getEmail()) ?>" name="email" /></br>
                <label for="apropos">A propos de vous : </label> 
                <textarea rows="1" cols="18" name="apropos"><?= htmlentities($info->getApropos()) ?></textarea></br>
                <input type="submit" value="modifier" name="submit" />
            </form>
    </div>
    <h3>Ajouter une photo</h3>
    <div class="ajouter_photos">
    <div class="error"><?= $error2 ?></div>
        <form enctype="multipart/form-data" action="" method="POST">
            <input name="photo" type="file" />
            <input type="submit" value="Envoyer le fichier"name="submit_photo" />
        </form>

    </div>
    <div style="margin-left:425px">
    <h3>Supprimer une photo</h3>
    <a href="index.php?page=supprimer_photo&pseudo=<?= htmlentities($info->getPseudo()) ?>">Voir les photos</a>
    </div>
