<h2 id="apropos">a propos de moi </h2>

<p class="presentation" >J'ai décidé de quiter  mon ancien metier (militaire) pour devenir developpeur web il y     a    plus dun ans  ,depuis , ayant apris le plus souvent sur google j'ai eu l'occasion de de participer a 3 mois de formation a 3w accademy suivi de 4 semaines consacrées a Symfony3 ce qui m'a permis de gagner en confiance 
et surtout en competences .Toujours motivé , je recherche actuellement l'occasion d'evoluer et de mettre en pratique mes nouvelles connaissances.
</p>

<?php require('apps/portfolio.php'); ?>
