<h2 id="contact">contact</h2>
<div class="contact">
<p><?=  $error ?></p>
<form action="#" method="POST">
    <div class="inputs_form">
    <label>nom</label><input class="nom" type="text" name="nom"/></br>
    <label>mail</label><input class="email" type="email" name="email"/>
    </div>
    <div class="textarea_form">
    <label>message</label><textarea class="message" name="message"></textarea>
    </div>
    <div class="submit">
    <input class="input_submit" type="submit" value="Envoyer" name="submit" />
    <input class="input_reset" type="reset" value="Effacer" name="effacer" />
    </div>



</form>
</div>
