<!DOCTYPE html>
<html lang="fr">
    <head>
        <title>titre</title>
        <!--<link type="text/css" rel="stylesheet" href="public/style/reset.css"/>-->
        <link type="text/css" rel="stylesheet" href="public/style/site.css"/>
        <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Denk+One|Original+Surfer" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Baloo+Tamma" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Ravi+Prakash" rel="stylesheet"> 
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
         
    </head>

    <body>
        <div class="container">

    <?php 

    require('apps/header.php');
    require('apps/content.php');
    require('apps/footer.php');


    ?>


    

        </div>
       
        <script type="text/javascript" src="public/js/main.js"></script>
    </body>

</html>
