
<header>
    <ul class="menu_site">
        <li><a href="index.php?page=acceuil">Acceuil</a></li>
        <li><a href="index.php?page=boutique">Produits</a></li>
        <li><a href="index.php?page=panier">Panier</a></li>
        <li><a href="index.php?page=logout">Deconexion</a></li>
        <li><a href="index.php?page=action_admin">Ajouter produit</a></li>
        
        
        
    </ul>
</header>
