
<h2>Nouveau password <?= $_SESSION['email'] ?></h2>
<div class="error"><?= $error ?></div>
<form action="" method="POST">
    <label for="password">Votre nouveau password  </label><br/>
    <input type="password" name="password" /></br>
    <label for="passwordBis">Confirmez le nouveau password  </label><br/>
    <input type="password" name="passwordBis" /></br>
    <input type="submit" name="submit_pwd" value="valider"/>
</form>
